[package]
name = "mdbook-rust-doc"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1"
clap = "3.0.0-beta.4"
serde = { version = "1", features = ["derive"] }
toml = "0.5"
syn = {version = "1", features = ["extra-traits"]}
shellexpand = "2.1"
proc-macro2 = "1"
