name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install mdbook
      run: cargo install mdbook
    - name: Build
      run: cargo build --verbose
    - name: Check test book
      run: bin/test-book.sh
